// Captures every screen and state for the designer handoff (demo AI mode).
import { chromium } from 'playwright'
import { readdirSync } from 'node:fs'
import { join } from 'node:path'

const BASE = process.env.BASE_URL ?? 'http://localhost:5173'
const OUT = 'docs/design-handoff/screens'
const fixtures = readdirSync('e2e/fixtures').map((f) => join('e2e/fixtures', f))
const browser = await chromium.launch({ args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--autoplay-policy=no-user-gesture-required'] })
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, permissions: ['microphone'] })
const page = await context.newPage()
page.on('dialog', (d) => d.accept())
const snap = (name) => page.screenshot({ path: `${OUT}/${name}.jpg`, type: 'jpeg', quality: 72 })
const wait = (ms) => page.waitForTimeout(ms)

await page.goto(BASE)
await snap('01-home-empty')
await page.getByRole('button', { name: 'New vlog' }).click()
await page.waitForURL(/\/clips$/)
await snap('02-clips-empty')
await page.locator('input[type=file]').setInputFiles(fixtures)
await wait(250)
await snap('03-clips-importing')
await page.waitForFunction((n) => document.querySelectorAll('ul li img').length >= n, fixtures.length, { timeout: 60000 })
await page.locator('ul li button[aria-label^="Star"]').first().click()
await wait(300)
await snap('04-clips-ready')
await page.getByRole('button', { name: 'Continue' }).click()
await page.waitForURL(/\/script$/)
await wait(300)
await snap('05-script-empty')
await page.getByPlaceholder('A rainy Sunday').fill('a sunny Saturday in the park')
await page.getByRole('button', { name: 'Write it for me' }).click()
await wait(150)
await snap('06-script-writing')
await page.waitForFunction(() => [...document.querySelectorAll('ol textarea')].length > 2, null, { timeout: 30000 })
await wait(400)
await snap('07-script-filled')
await page.mouse.wheel(0, 900)
await wait(300)
await snap('08-script-settings')
await page.getByRole('button', { name: 'Continue' }).click()
await page.waitForURL(/\/voice$/)
await wait(300)
await snap('09-voice-ai')
await page.getByRole('radio', { name: /Record my own/ }).click()
await wait(200)
await snap('10-voice-record')
await page.getByRole('button', { name: 'Record' }).first().click()
await wait(300)
await snap('11-teleprompter')
await page.getByRole('button', { name: 'Start recording' }).click()
await wait(900)
await snap('12-teleprompter-recording')
await page.getByRole('button', { name: 'Stop recording' }).click()
await wait(1500)
await page.getByRole('button', { name: 'Close' }).click()
await wait(300)
await snap('13-voice-record-progress')
// error state: generate with lines still unrecorded
const projectUrl = page.url().replace(/\/voice$/, '')
await page.goto(`${projectUrl}/generate`)
await page.waitForSelector('text=Try again', { timeout: 60000 })
await snap('14-generate-error')
await page.goto(`${projectUrl}/voice`)
await page.getByRole('radio', { name: /No voiceover/ }).click()
await wait(200)
await snap('15-voice-none')
await page.getByRole('radio', { name: /AI voice/ }).click()
await page.getByRole('button', { name: 'Make my vlog' }).click()
await page.waitForURL(/\/generate$/)
await wait(700)
await snap('16-generate-progress')
await page.waitForURL(/\/edit$/, { timeout: 90000 })
await page.waitForFunction(() => !document.body.innerText.includes('Mixing audio'), null, { timeout: 30000 })
await page.getByRole('button', { name: 'Play' }).first().click()
await wait(1300)
await page.getByRole('button', { name: 'Pause' }).first().click()
await snap('17-editor-scenes')
await page.locator('ol[aria-label=Scenes] li button').nth(1).click()
await wait(400)
await snap('18-scene-sheet')
await page.getByRole('button', { name: 'Swap' }).first().click()
await wait(300)
await snap('19-scene-swap')
await page.getByRole('button', { name: 'Trim' }).first().click()
await wait(300)
await snap('20-scene-trim')
await page.getByRole('button', { name: 'Close' }).click()
for (const [i, tab] of [['21', 'Voice'], ['22', 'Music'], ['23', 'Style']]) {
  await page.getByRole('button', { name: tab, exact: true }).click()
  await wait(250)
  await snap(`${i}-editor-${tab.toLowerCase()}`)
}
await page.getByRole('button', { name: 'Scenes', exact: true }).click()
await page.getByRole('button', { name: 'Export', exact: true }).click()
await wait(300)
await snap('24-export-ready')
await page.getByRole('button', { name: 'Export video' }).click()
await wait(3000)
await snap('25-export-rendering')
await page.waitForSelector('text=/Ready ·/', { timeout: 180000 })
await wait(500)
await snap('26-export-done')
await page.getByRole('button', { name: 'Close' }).click()
await page.goto(BASE)
await page.waitForSelector('text=Your vlogs')
await wait(400)
await snap('27-home-with-vlogs')
await page.setViewportSize({ width: 1280, height: 860 })
await wait(300)
await snap('28-desktop-home')
await page.goto(`${projectUrl}/edit`)
await page.waitForSelector('ol[aria-label=Scenes] li', { timeout: 30000 })
await wait(1500)
await snap('29-desktop-editor')
await page.goto(`${projectUrl}/script`)
await wait(800)
await snap('30-desktop-script')
await browser.close()
console.log('done')
