// Captures every screen and state (demo AI mode) at phone and desktop sizes.
import { chromium } from 'playwright'
import { mkdirSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const BASE = process.env.BASE_URL ?? 'http://localhost:5173'
const OUT = process.env.OUT ?? 'docs/screens'
const ONLY = process.env.ONLY // 'phone' | 'desktop'
mkdirSync(OUT, { recursive: true })
const fixtures = readdirSync('e2e/fixtures').map((f) => join('e2e/fixtures', f))
const browser = await chromium.launch({ args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--autoplay-policy=no-user-gesture-required'] })

async function run(device) {
  const phone = device === 'phone'
  const context = await browser.newContext({ viewport: phone ? { width: 390, height: 844 } : { width: 1360, height: 900 }, deviceScaleFactor: phone ? 2 : 1, permissions: ['microphone'] })
  const page = await context.newPage()
  page.on('pageerror', (e) => console.log('pageerror', e.message))
  const snap = (name) => page.screenshot({ path: `${OUT}/${device}-${name}.jpg`, type: 'jpeg', quality: 74 })
  const wait = (ms) => page.waitForTimeout(ms)
  const click = (name, opts = {}) => page.getByRole('button', { name, ...opts }).filter({ visible: true }).first().click()

  await page.goto(BASE)
  await wait(600)
  await snap('01-home-first-visit')
  await click('New vlog')
  await page.waitForURL(/\/clips$/)
  await wait(300)
  await snap('02-clips-empty')
  await page.locator('input[type=file]').setInputFiles(fixtures)
  await wait(250)
  await snap('03-clips-importing')
  await page.waitForFunction((n) => document.querySelectorAll('ul li img').length >= n, fixtures.length, { timeout: 60000 })
  await page.locator('ul li button[aria-label^="Star"]').first().click()
  await wait(300)
  await snap('04-clips-ready')
  await click('Continue')
  await page.waitForURL(/\/script$/)
  await wait(400)
  await snap('05-script-empty')
  await page.getByPlaceholder('a lazy park day').fill('a sunny Saturday in the park')
  await click('Write it for me')
  await wait(120)
  await snap('06-script-writing')
  await page.waitForFunction(() => [...document.querySelectorAll('ol input')].length > 2, null, { timeout: 30000 })
  await wait(400)
  await snap('07-script-filled')
  await click('Rewrite with AI')
  await wait(300)
  await snap('08-script-replace-confirm')
  await click('Keep mine')
  await click('Continue')
  await page.waitForURL(/\/voice$/)
  await wait(400)
  await snap('09-voice-ai')
  await page.getByRole('radio', { name: /Record my own/ }).click()
  await wait(200)
  await snap('10-voice-record')
  await click('Open teleprompter')
  await wait(300)
  await snap('11-teleprompter')
  await click('Start recording')
  await wait(1000)
  await snap('12-teleprompter-recording')
  await click('Stop recording')
  await wait(1600)
  await click('Close teleprompter')
  await wait(300)
  await snap('13-voice-record-progress')
  const projectUrl = page.url().replace(/\/voice$/, '')
  await page.goto(`${projectUrl}/generate`)
  await page.waitForSelector('text=Try again', { timeout: 60000 })
  await wait(300)
  await snap('14-make-error')
  await page.goto(`${projectUrl}/voice`)
  await page.getByRole('radio', { name: /No voiceover/ }).click()
  await wait(200)
  await snap('15-voice-none')
  await page.getByRole('radio', { name: /AI voice/ }).click()
  await click('Make my vlog')
  await page.waitForURL(/\/generate$/)
  await wait(900)
  await snap('16-make-progress')
  await page.waitForURL(/\/edit(\?|$)/, { timeout: 90000 })
  await page.waitForFunction(() => !document.body.innerText.includes('Mixing audio'), null, { timeout: 30000 })
  await wait(1300)
  if (await page.getByRole('button', { name: 'Pause' }).count()) await page.getByRole('button', { name: 'Pause' }).first().click()
  await snap('17-edit-scenes')
  await page.locator('ol[aria-label=Scenes] li button').nth(1).click()
  await wait(500)
  await snap('18-edit-scene-editor')
  await page.mouse.wheel(0, 700)
  await wait(300)
  await snap('19-edit-scene-editor-trim')
  await click('All scenes')
  await page.evaluate(() => window.scrollTo(0, 0))
  for (const [i, tab] of [['20', 'Voice'], ['21', 'Music'], ['22', 'Style']]) {
    await page.getByLabel('Edit panels').getByRole('button', { name: tab, exact: true }).click()
    await wait(250)
    await snap(`${i}-edit-${tab.toLowerCase()}`)
  }
  await page.getByLabel('Edit panels').getByRole('button', { name: 'Scenes', exact: true }).click()
  if (phone) {
    await click('Tell the AI')
    await wait(300)
    await snap('23-edit-tell-ai')
    await page.getByRole('button', { name: 'Close' }).click()
  }
  await click(phone ? 'Export' : 'Export video', { exact: true })
  await wait(400)
  await snap('24-export-ready')
  await page.getByRole('dialog').getByRole('button', { name: 'Export video' }).click()
  await wait(3000)
  await snap('25-export-rendering')
  await page.waitForSelector('text=/Ready ·/', { timeout: 180000 })
  await wait(500)
  await snap('26-export-done')
  await page.getByRole('button', { name: 'Close' }).click()
  await page.goto(BASE)
  await page.waitForSelector('text=Your vlogs')
  await wait(600)
  await snap('27-home')
  await page.getByRole('button', { name: /More options/ }).first().click()
  await wait(300)
  await snap('28-home-delete')
  await context.close()
}

for (const d of ['phone', 'desktop']) if (!ONLY || ONLY === d) await run(d)
await browser.close()
console.log('done')
